verbose: false
instrumentation:
  root: .
  default-excludes: true
  excludes: ['hydro.conf.js', 'lib/cli']
  embed-source: false
  variable: __coverage__
  compact: true
  preserve-comments: false
  complete-copy: false
  save-baseline: false
  baseline-file: ./coverage/coverage-baseline.json
reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage
check:
  global:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
